version: "3.8"

services:
  blog-redis:
    image: redis
    container_name: "blog-redis"
    ports:
      - "6379:6379"
    networks:
      - fullstack

  db:
    image: postgres:12.2-alpine
    container_name: "db"
    command: postgres -c listen_addresses='*'
    ports:
      - "5432:5432"
    environment: 
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - fullstack
    volumes:
      - database_postgres:/var/lib/postgresql/data

  blog-v2:
    build: .
    container_name: "backend"
    environment:
      TEST: "test"
      DB_USERNAME: "postgres"
      DB_PASSWORD: "postgres"
      DB_DB: "postgres"
      DB_HOST: "db"
      DB_TABLE: "postgres"
      DB_PORT: "5432"
      ENV: "prod"
      REDIS_HOST: "blog-redis"
      REDIS_PORT: "6379"
    ports:
      - "4000:4000"
    depends_on: 
      - db
      - blog-redis
    networks:
      - fullstack

volumes:
  database_postgres:

networks:
  fullstack:
    driver: bridge
